version: 2022.07.14.{build}
skip_tags: true
image: Visual Studio 2022
configuration: Debug
platform: Any CPU
before_build:
  - nuget restore updater\updater.sln
build:
  project: updater/updater.sln
  verbosity: normal
