version: 2020.10.06.{build}
skip_tags: true
image: Visual Studio 2019
configuration: Debug
platform: x86
before_build:
  - nuget restore updater\updater.sln
build:
  project: updater/updater.sln
  verbosity: normal
