name: Build with Mono on Ubuntu 20.04

on: push

jobs:
  build_mono_ubuntu_20_04:
    runs-on: ubuntu-20.04
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v2
      - name: Install Debian packages
        run: |
          sudo apt-get update
          sudo apt-get install -y git mono-complete mono-xbuild nuget
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE && pwd && ls -lah
          nuget restore ./updater/updater.sln
          xbuild ./updater/updater.csproj
          xbuild ./moz-checksum-generator/moz-checksum-generator.csproj
