name: .NET on Ubuntu

on: push

jobs:
  dotnet_ubuntu_20_04:
    runs-on: ubuntu-20.04
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3
      - name: Install Debian packages
        run: |
          sudo apt-get update
          sudo apt-get install -y git
      - name: Install .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE && pwd && ls -lah
          dotnet restore ./updater/updater.csproj
          dotnet restore ./updater-test/updater-test.csproj
          dotnet build ./updater/updater.csproj
          dotnet build ./updater-test/updater-test.csproj
          # Unfortunately, WinForms applications cannot be built on Linux.
          # So ./moz-checksum-generator/moz-checksum-generator.csproj has to be
          # excluded from the build.
